
# Scripts Para ingresar la info a la DB de forma rápida!!!

from db_manager import DBManager_sqlite

# instance of DB
db_manager_sqlite = DBManager_sqlite()


data = [
    ("SKAR", "AXM", "EL EDEN", "ARMENIA", 4.454, -75.765, 2, 0,	2251, 3979, "", "True",
     "True", "True", "True", "True", "False", "True", "False", "True", "False"	, 2, ""),
    ("SKAS", "PUU", "TRES DE MAYO", "PUERTO ASIS", 0.3507, -76.501, 1, 0, 1608, 815, "", "True",
     "True", "True", "False", "False", "False", "False", "True", "False", "False"	, 2, ""),
    ("SKBC", "N/A", "LAS FLORES",	"EL BANCO", 9.045, -73.975, 10, 0, 1330, 111, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False"	, 2, ""),
    ("SKBG", "BGA", "PALONEGRO",	"BUCARAMANGA", 7.126, -73.185, 17, 0, 2256, 3902, "", "True",
     "True", "True", "True", "True", "True", "True", "False", "True", "False"	, 2, ""),
    ("SKBO", "BOG", "ELDORADO",	"BOGOTA", 4.701, -74.147, 13, 13, 3799, 8360, "", "True",
     "True", "True", "True", "False", "False", "True", "False", "True", "False"	, 3, ""),

    ("SKBQ", "BAQ", "ERNESTO CORTISSOZ", "BARRANQUILLA", 10.889, -74.781, 5, 0, 3050, 98, "",
     "True", "True", "True", 	"True", "False", "True", "True", "False", "True", "False"	, 3, ""),
    ("SKBS", "BSC", "JOSE CELESTINO MUTIS",	"BAHIA SOLANO", 6.203, -77.394, 18, 0, 1210, 79, "",
     "True", "False", "False", 	"False", "False", "False", "False", "False", "False", "False"	, 1, ""),
    ("SKBU", "BUN", "GERARDO TOBAR LOPEZ",	"BUENAVENTURA", 3.819, -76.99, 9, 0, 1196, 48, "", "True",
     "True", "False", 	"False", "False", "False", "False", "False", "True", "False"	, 1, ""),
    ("SKCC", "CUC", "CAMILO DAZA",	"CUCUTA", 7.928, -72.511, 16, 20, 1981, 1098, "", "True",
     "True", "True", 	"True", "True", "True", "True", "False", "True", "True"	, 3, ""),
    ("SKCD", "COG", "MANDINGA", "CONDOTO", 5.072, -76.676, 9, 0, 1213, 215, "", "True",
     "False", "False", 	"False", "False", "False", "False", "False", "False", "False"	, 2, ""),

    ("SKCG", "CTG", "RAFAEL NUNEZ", "CARTAGENA", 10.442,  -75.513, 1, 0, 2649, 4, "", "True",
     "True", "True", 	"True", "False", "True", "False", "False", "True", "False"	, 2, ""),
    ("SKCL", "CLO", "ALFONSO BONILLA ARAGON", "CALI", 3.543, -76.381, 2, 0, 3015, 3162, "",
     "True", "True", "True", 	"True", "True", "False", "True", "False", "True", "False"	, 2, ""),
    ("SKCO", "TCO", "LA FLORIDA", "TUMACO", 1.814, -78.749, 5, 0, 1602, 8, "", "True",
     "True", "True", 	"True", "False", "True", "False", "False", "True", "False"	, 1, ""),
    ("SKCZ", "CZU", "LAS BRUJAS", "COROZAL", 9.332, -75.286, 2, 0, 1520, 568, "", "True",
     "True", "True", 	"False", "False", "False", "False", "False", "True", "False"	, 1, ""),
    ("SKEJ", "EJA", "YARIGUIES", "BARRANCABERMEJA", 7.024, -73.807, 4, 0, 1809, 413, "", "True",
     "True", "True", 	"True", "True", "False", "False", "False", "True", "False"	, 1, ""),

    ("SKFL", "FLA", "GUSTAVO ARTUNDUAGA PAREDES", "FLORENCIA", 1.59, -75.564, 12, 0, 1400, 803, "",
     "True", "True", "True", 	"True", "True", "False", "False", "False", "False", "True"	, 3, ""),
    ("SKGI", "N/A", "SANTIAGO VILA", "GIRARDOT", 4.276, -74.797, 1, 0, 1599, 937, "", "True",
     "True", "False", 	"False", "False", "False", "False", "False", "True", "True"	, 2, ""),
    ("SKGO", "N/A", "SANTA ANA", "CARTAGO", 4.758, -75.956, 1, 0, 2202, 2979, "", "True",
     "True", "True", 	"False", "False", "False", "False", "False", "False", "True"	, 2, ""),
    ("SKGP", "GPI", "GUAPI", "GUAPI", 2.57, -77.898, 1, 0, 1220, 72, "", "True", "True",
     "True", "False", "False", "False", "False", "True", "False", "False", 2, ""),
    ("SKGY", "N/A", "GUAYMARAL", "GUAYMARAL", 4.812, -74.065, 11, 0, 1749, 8390, "", "True",
     "False", "False", 	"False", "False", "False", "False", "False", "False", "False"	, 1, ""),
    ("SKIB", "IBE", "PERALES", "IBAGUE", 4.421, -75.133, 14, 0, 1800, 3114, "", "True",
     "True", "True", 	"True", "False", "False", "False", "False", "True", "False"	, 2, ""),
    ("SKIP", "IPI", "SAN LUIS", "IPIALES", 0.5986, -77.672, 6, 0, 1772, 6765, "", "True",
     "True", "True", 	"True", "False", "False", "False", "False", "True", "False"	, 2, ""),

    ("SKLC", "N/A", "ANTONIO ROLDAN BETANCOURT", "CAREPA", 7.812, -76.716, 15, 0, 2187, 46, "",
     "True", "True", "True", "True", "False", "True", "False", "False", "True", "False", 2, ""),
    ("SKLM", "N/A", "LA MINA", "LA MINA", 11.232, -72.49, 10, 0, 1499, 332, "", "True",
     "True", "True",	"True", "True", "True", "True", "False", "True", "False"	, 2, ""),
    ("SKLT", "LET", "ALFREDO VASQUEZ COBO", "LETICIA", -4.13, -69.943, 3, 0, 2104, 314, "",
     "True", "True", "True",	"True", "False", "True", "True", "False", "True", "False"	, 1, ""),
    ("SKMD", "EOH", "OLAYA HERRERA", "MEDELLIN", 6.22, -75.591, 2, 0, 2511, 4940, "", "True",
     "False", "False", 	"True", "False", "False", "False", "False", "False", "False"	, 2, ""),
    ("SKMG", "MGN", "BARACOA", "MAGANGUE", 9.283, -74.839, 10, 0, 1499, 178, "", "True",
     "False", "False", 	"False", "False", "False", "False", "False", "False", "False"	, 2, ""),
    ("SKMR", "MTR", "LOS GARZONES", "MONTERIA", 8.824, -75.826, 14, 0, 1918, 36, "", "True",
     "True", "True", 	"True", "True", "False", "True", "False", "True", "False"	, 2, ""),
    ("SKMU", "MVP", "FABIO ALBERTO LEON BENTLEY", "MITU", 1.254, -70.234, 2, 0, 1879, 604, "",
     "True", "True", "False", 	"False", "False", "False", "False", "False", "True", "False"	, 1, ""),
    ("SKMZ", "MZL", "LA NUBIA", "MANIZALES", 5.03, -75.465, 10, 0, 1391, 6973, "", "True",
     "True", "True", 	"True", "True", "False", "False", "False", "True", "False"	, 3, ""),
    ("SKNV", "NVA", "BENITO SALAS", "NEIVA", 2.942387, -75.294, 2, 0, 1865, 1440, "", "True",
     "True", "True", 	"True", "False", "False", "False", "False", "True", "False"	, 1, ""),
    ("SKOC", "OCV", "AGUAS CLARAS", "OCANA", 8.315, -73.358, 1, 0, 1099, 3852, "", "True",
     "False", "False", 	"False", "False", "False", "False", "False", "False", "False"	, 2, ""),
    ("SKOT", "OTU", "OTU", "OTU", 7.01, -74.715, 18, 0, 929, 2000, "", "True", "False",
     "False", "False", "False", "False", "False", "False", "False", "False"	, 2, ""),
    ("SKPB", "N/A", "PUERTO BOLIVAR", "PUERTO BOLIVAR", 12.221, -71.985, 9, 0, 1591, 90, "", "True", "True", "False",
     "True", "False", "False", "False", "True", "False", "False", 2, "The STAR is similar to an NDB aproach."),

    ("SKPC", "PCR", "PUERTO CARRENO", "PUERTO CARRENO", 6.184, -67.493, 7, 0, 1800, 180, "",
     "True", "True", "True", 	"True", "False", "False", "False", "False", "True", "False", 1, ""),
    ("SKPE", "PEI", "MATECANA", "PEREIRA", 4.813, -75.739, 8, 0, 2050, 4418, "", "True",
     "True", "True", "True", "False", "False", "True", "False", "True", "False", 2, ""),
    ("SKPI", "N/A", "PITALITO", "PITALITO", 1.858, -76.086, 6, 0, 1499, 4212, "", "True",
     "False", "False",	"False", "False", "False", "False", "False", "False", "False"	, 2, ""),
    ("SKPP", "PPN", "GUILLERMO LEON VALENCIA", "POPAYAN", 2.454, -76.61, 7, 0, 1853, 5687, "",
     "True", "True", "True", "True", "False", "False", "False", "False", "True", "False"	, 1, ""),
    ("SKPS", "PSO", "ANTONIO NARINO", "PASTO", 1.396, -77.291, 2, 0, 2204, 5951, "", "True",
     "True", "True", "True", "False", "False", "True", "False", "True", "False"	, 2, ""),
    ("SKPV", "PVA", "EL EMBRUJO", "PROVIDENCIA", 13.357, -81.358, 17, 0, 1167, 10, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False"	, 1, ""),
    ("SKQU", "N/A", "MARIQUITA", "MARIQUITA", 5.213, -74.884, 1, 0, 1795, 1531,	"", "True",
     "True", "False", "False", "False", "False", "False", "False", "True", "False", 1, ""),
    ("SKRG", "MDE", "JOSE MARIA CORDOVA", "RIONEGRO", 6.164, -75.423, 1, 0, 3460, 7025, "",
     "True", "True", "True", "True", "False", "False", "True", "False", "False",	"False", 2, ""),

    ("SKRH", "RCH", "ALMIRANTE PADILLA", "RIOHACHA", 11.526, -72.926, 10, 0, 1900, 48, "", "True",
     "True", "True", "True", "True", "True", "False", "False", "True", "False", 1, ""),
    ("SKSA", "RVE", "LOS COLONIZADORES", "SARAVENA", 6.958, -71.855, 15, 0, 1205, 680, "",
     "True", "True", "True", "True", "False", "False", "False", "True", "False", "False", 2, ""),
    ("SKSJ", "SJE", "JORGE E GONZALEZ TORRES", "SAN JOSE DEL GUAVIARE", 2.579, -72.639, 1, 0, 1410, 574,
     "", "True", "True", "True", "True", "False", "False", "False", "False", "True", "False", 1, ""),
    ("SKSM", "SMR", "SIMON BOLIVAR", "SANTA MARTA", 11.119, -74.231, 1, 0, 1698, 22, "", "True",
     "True", "True", "True", "False", "True", "False", "False", "True", "False", 1, ""),
    ("SKSP", "ADZ", "GUSTAVO ROJAS PINILLA", "SAN ANDRES ISLAND", 12.583, -81.711, 6, 0, 2402, 19, "",
     "True", "True", "True", "True", "True", "False", "False", "False", "True", "False", 2, ""),
    ("SKSV", "SVI", "EDUARDO FALLA SOLANO", "SAN VINCENTE DE CAGUAN", 2.152, -74.766, 13, 0, 1292, 920,
     "", "True", "True", "True", "True", "False", "False", "False", "False", "True", "False", 1, ""),
    ("SKTD", "TDA", "TRINIDAD", "TRINIDAD", 5.43, -71.658, 5, 0, 1100, 532, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKTM", "TME", "TAME", "TAME", 6.451, -71.76, 6, 0, 1598, 1050, "", "True", "True",
     "True", "False", "False", "False", "False", "False", "True", "False", 1, ""),
    ("SKTU", "TRB", "GONZALO MEJIA", "TURBO", 8.074, -76.741, 16, 0, 949,	7, "",	"True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKUC", "AUC", "SANTIAGO PEREZ", "ARAUCA", 7.069, -70.737, 11, 0, 2100, 420, "", "True",
     "True", "True", "True", "True", "True", "False", "False", "True", "False", 1, ""),
    ("SKUI", "UIB", "EL CARANO", "QUIBDO", 5.691, -76.641, 13, 0, 1401, 204, "", "True",
     "True", "True", "True", "True", "True", "True", "False", "True", "False", 2, ""),
    ("SKUL", "ULQ", "FARFAN", "TULUA", 4.088, -76.235, 1, 0, 1800, 3132, "",
     "True", "True", "False", "False", "False", "False", "False", "False", "True", "False", 2, ""),
    ("SKVP", "VUP", "ALFONSO LOPEZ PUMAREJO", "VALLEDUPAR", 10.435,  -73.249, 2, 0, 2100, 483, "",
     "True", "True", "True", "False", "False", "False", "False", "False", "True", "False", 1, ""),
    ("SKVV", "VVC", "VANGUARDIA", "VILLAVICENCIO", 4.168,  -73.614, 5, 0, 1700, 1394, "",
     "True", "True", "True", "True", "False", "True", "False", "False", "False", "True", 3, ""),
    ("SKYP", "N/A", "EL YOPAL", "EL YOPAL", 5.319, -72.384, 5, 0, 2245, 1028, "", "True",
     "True", "True", "True", "False", "False", "True", "False", "True", "False", 2, ""),
    ("SKAG", "N/A", "HACARITAMA", "HACARITAMA", 8.249103, -73.585, 11, 0, 1167, 700, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKBN", "N/A", "BUENAVISTA", "BUENAVISTA", 10.881843, -729.036, 3, 0, 1504, 850, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKCA", "N/A", "CAPURGANA", "CAPURGANA", 8.630946, -77.347946, 3, 0, 910, 13, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKCM", "N/A", "CIMITARRA", "CIMITARRA", 6.377662, -73.974770, 15, 0, 1499, 538, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKCV", "N/A", "COVEÑAS", "COVEÑAS", 9.397256, -75.695946, 5, 0, 1339, 31, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKEB", "N/A", "EL BAGRE", "EL BAGRE", 7.587142, -74.798256, 1, 0, 1460, 286, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKMP", "N/A", "SAN BERNARDO", "SAN BERNARDO", 9.253409, -74.439667, 2, 0, 1239, 60, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKOR", "N/A", "ORITO", "ORITO", 0.670359, -76.817360, 16, 0, 910, 1142, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKPA", "N/A", "JUAN JOSE RONDON", "PAIPA", 5.767467, -73.114944, 4, 0, 1698,	8205, "", "True",
     "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKPZ", "N/A", "PAZ DE ARIPORO", "PAZ DE ARIPORO", 5.870683, -71.904259, 4, 0, 1420, 900, "",
     "True", "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKSO", "N/A", "ALBERTO LLERAS CAMARGO", "SOGAMOSO", 5.669713, -72.975746, 4, 0, 1880, 8155, "",
     "True", "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
    ("SKVG", "N/A", "VILLA GARZON", "VILLA GARZON", 0.984520, -766.067, 16, 0, 1327, 1248, "",
     "True", "False", "False", "False", "False", "False", "False", "False", "False", "False", 2, ""),
]


diff_flight_data = [
    ("SKPP", "SKPE", 2, ""),
    ("SKPP", "SKIP", 3,
     "Keep an eye on the MEA.  Can you identify where the Galeras volcano is?"),
    ("SKPP", "SKAS", 2, ""),
    ("SKPP", "SKGP", 2, ""),
    ("SKPP", "SKNV", 1, ""),
    ("SKVV", "SKBO", 2, ""),
    ("SKVV", "SKPE", 2, "Don`t follow any arrival. Keep an eye on the MEA before PEI VOR."),
    ("SKVV", "SKPE", 2, "Make EPO3F arrival."),
    ("SKVV", "SKAR", 3, "Select any STAR with an arc."),
    ("SKVV", "SKAR", 3, "Make EPO5A arrival."),
    ("SKVV", "SKAR", 3, "For a more interesting flight, make the missed approach."),
    ("SKVV", "SKGO", 2, "For a more interesting flight, make the missed approach."),
    ("SKVV", "SKGO", 2, ""),
    ("SKVV", "SKYP", 2, ""),
    ("SKVV", "SKSJ", 2, ""),
    ("SKVV", "SKNV", 1, ""),
    ("SKBO", "SKMZ", 3, "Make an arrival with an arc."),
    ("SKBO", "SKMZ", 3, "Make your arrival via MATRO."),
    ("SKBO", "SKVV", 2, ""),
    ("SKBO", "SKBU", 2, ""),
    ("SKBO", "SKEJ", 2, ""),
    ("SKBO", "SKYP", 2, ""),
    ("SKBO", "SKPP", 1, ""),
    ("SKBO", "SKPE", 2, ""),
    ("SKBO", "SKPE", 2, "Make your arrival via AXM-IRIGI."),
    ("SKBO", "SKPE", 2, "Make EPO3F arrival."),
    ("SKBO", "SKAR", 2, ""),
    ("SKBO", "SKGO", 3, ""),
    ("SKBO", "SKRG", 2, ""),
    ("SKBO", "SKCG", 2, ""),
    ("SKBO", "SKBQ", 2, ""),
    ("SKBO", "SKSM", 2, ""),
    ("SKBO", "SKRH", 2, ""),
    ("SKBO", "SKCL", 2, ""),
    ("SKBO", "SKCL", 3, "The routes via EKARA and OREGA are not operative today.  Find a different route."),
    ("SKBO", "SKGI", 3, ""),
    ("SKBO", "SKIB", 3, "Everything will happen very fast.  Control your airspeed to have enough time for your duties."),
    ("SKBO", "SKIB", 3, "Everything will happen very fast.  Control your airspeed to have enough time for your duties.  For a more interesting flight, make the missed approach and proceed to SKAR as alternate."),
    ("SKBO", "SKRG", 2,
     "Routes via MQU or NIRSO are not possible today.  Find a different route."),
    ("SKGO", "SKRG", 1, ""),
    ("SKGO", "SKRG", 3, "Routes via MATRO, AKSIM or MZL VOR are not possible today.  Find a different route."),
    ("SKGO", "SKRG", 2, "Routes via MATRO or AKSIM are not possible today.  Find a different route."),
    ("SKGO", "SKQU", 2, ""),
    ("SKGO", "SKMZ", 3, "Keep an eye on the MEA from PEI VOR to MZL VOR."),
    ("SKSM", "SKMR", 2, ""),
    ("SKSM", "SKCG", 2, ""),
    ("SKSM", "SKMR", 2, ""),
    ("SKSM", "SKLM", 2, ""),
    ("SKSM", "SKPE", 2, "Do not enter PEI TMA via MATRO."),
    ("SKSM", "SKCC", 3, ""),
    ("SKRH", "SKCG", 2, ""),
    ("SKRH", "SKSM", 3, "Proceed via IRONU and DOTRO."),
    ("SKRH", "SKSM", 2, ""),
    ("SKRH", "SKCC", 2, ""),
    ("SKRH", "SKYP", 2, ""),
    ("SKCG", "SKSP", 2, ""),
    ("SKCG", "SKSM", 1, ""),
    ("SKCG", "SKRH", 1, ""),
    ("SKCG", "SKVP", 2, "The route via UMPUR is not possible today.  Find a different route."),
    ("SKCG", "SKPE", 2, "The routes via MATRO or AKSIM are not operative today.  Find a different route."),
    ("SKSP", "SKPE", 2, ""),
    ("SKSP", "SKBQ", 1, ""),
    ("SKSP", "SKPV", 2, ""),
    ("SKSP", "SKRH", 2, ""),
    ("SKBQ", "SKMZ", 3, ""),
    ("SKBQ", "SKVP", 2, ""),
    ("SKBQ", "SKRH", 1, ""),
    ("SKBQ", "SKCZ", 1, ""),
    ("SKPE", "SKRG", 2, ""),
    ("SKPE", "SKCG", 1, ""),
    ("SKPE", "SKBQ", 2, ""),
    ("SKPE", "SKIB", 2, ""),
    ("SKPE", "SKMZ", 3, "Take off from RWY 08.  Maximum altitud 10.000'"),
    ("SKPE", "SKBO", 2, ""),
    ("SKPE", "SKCL", 3, ""),
    ("SKNV", "SKCL", 2, "Keep an eye on the MEA from NVA to EDPES"),
    ("SKNV", "SKGI", 1, ""),
    ("SKNV", "SKIB", 1, "For a more interesting flight, make the missed approach."),
    ("SKNV", "SKPE", 2, ""),
    ("SKNV", "SKPP", 1, ""),
    ("SKAR", "SKRG", 1, ""),
    ("SKAR", "SKIB", 3, ""),
    ("SKAR", "SKMZ", 3, "Maximum altitude for this flight is 10.000'"),
    ("SKAR", "SKGO", 3, "For a more interesting flight, make the missed approach."),
    ("SKAR", "SKMZ", 3, "Don't take PEI W3 MATRO."),
    ("SKAR", "SKCL", 1, ""),
    ("SKAR", "SKPP", 1, ""),
    ("SKAR", "SKBU", 1, ""),
    ("SKIP", "SKAS", 2, ""),
    ("SKIP", "SKPS", 2, ""),
    ("SKAS", "SKPS", 2, "NDB is for navigation masters.  Are your up for the challenge?"),
    ("SKAS", "SKIP", 2, "NDB is for navigation masters.  Are your ready?"),
    ("SKCL", "SKRG", 1, ""),
    ("SKCL", "SKBO", 2, ""),
    ("SKCL", "SKBQ", 2, ""),
    ("SKCL", "SKSP", 2, ""),
    ("SKCL", "SKPP", 2, "Take route G675."),
    ("SKCL", "SKPP", 1, "Take route R567."),
    ("SKCL", "SKPE", 1, ""),
    ("SKCL", "SKPE", 3, "Due to military exercises, routes via ULQ VOR are nor possible today.  Find a different route."),
    ("SKCL", "SKPE", 2, "For a more interesting flight, make the missed approach."),
    ("SKBG", "SKCC", 3, ""),
    ("SKBG", "SKCC", 3, "For a more interesting flight, make the missed approach...and then return to SKBG."),
    ("SKBG", "SKSA", 2, ""),
    ("SKBG", "SKRG", 1, ""),
    ("SKBG", "SKBO", 2, ""),
    ("SKBG", "SKVP", 1, ""),
    ("SKBG", "SKYP", 3, "Make the VOR-Z approach.  Keep an eye on the MHA."),
    ("SKBG", "SKYP", 2, ""),
    ("SKBG", "SKUC", 2, ""),
    ("SKBG", "SKPE", 2, ""),
    ("SKUC", "SKCC", 2, ""),
    ("SKUC", "SKUI", 1, ""),
    ("SKUI", "SKBG", 3, ""),
    ("SKUI", "SKPE", 3, "For a more interesting flight, make the missed approach. Then proceed to SKMZ or SKAR as alternate."),
    ("SKUI", "SKEJ", 2, ""),
    ("SKUI", "SKMR", 1, ""),
    ("SKUI", "SKCL", 1, ""),
    ("SKUI", "SKMZ", 3, ""),
    ("SKUI", "SKMZ", 3, "For a more interesting flight, make the missed approach."),
    ("SKUI", "SKMZ", 3, "For a more interesting flight, make the missed approach. Then proceed to SKPE or SKAR as alternate."),
    ("SKUI", "SKGP", 2, ""),
    ("SKUI", "SKPE", 2, ""),
    ("SKRG", "SKUI", 2, ""),
    ("SKRG", "SKAR", 2, "Proceed via MATRO"),
    ("SKRG", "SKVV", 2, ""),
    ("SKRG", "SKAR", 2, "Proceed via AKSIM"),
    ("SKRG", "SKBO", 3, "Arrivals via MQU VOR are not possible today. Find a different route."),
    ("SKRG", "SKPE", 1, ""),
    ("SKRG", "SKBO", 2, ""),
    ("SKRG", "SKBQ", 3, "For a more interesting flight, make the missed approach."),
    ("SKRG", "SKCG", 2, ""),
    ("SKPS", "SKIP", 3, ""),
    ("SKPS", "SKIP", 3, "For a more interesting flight, make the missed approach."),
    ("SKPS", "SKIP", 3, "For a more interesting flight, make the missed approach.  Then return to SKPS as alternate."),
    ("SKPS", "SKAS", 3, "Practice the NDB approach!"),
    ("SKPS", "SKCO", 3, "For a more interesting flight, make the missed approach. Then proceed to SKIP as alternate."),
    ("SKPS", "SKCO", 1, ""),
    ("SKCO", "SKPS", 2, ""),
    ("SKCO", "SKPS", 3, "For a more interesting flight, depart runway 24."),
    ("SKCO", "SKGP", 2, "Ready for an NDB approach!?"),
    ("SKCO", "SKPS", 3, "For a more interesting flight, make the missed approach. Then proceed to SKIP as alternate."),
    ("SKRG", "SKSM", 2, ""),
    ("SKRG", "SKRH", 1, ""),
    ("SKRG", "SKCL", 2, ""),
    ("SKMR", "SKVP", 1, ""),
    ("SKMR", "SKRH", 2, ""),
    ("SKMR", "SKBG", 2, ""),
    ("SKMR", "SKYP", 2, ""),
    ("SKLC", "SKAR", 2, ""),
    ("SKLC", "SKTM", 1, ""),
    ("SKMR", "SKBQ", 1, ""),
    ("SKCC", "SKUC", 2, ""),
    ("SKCC", "SKYP", 2, ""),
    ("SKCC", "SKUI", 1, ""),
    ("SKCC", "SKLC", 2, ""),
    ("SKCC", "SKVP", 1, ""),
    ("SKCC", "SKVP", 2, "For a more interesting flight, make the missed approach. Then proceed to SKBQ as alternate."),
    ("SKCC", "SKMR", 2, ""),
    ("SKCC", "SKSM", 2, ""),
    ("SKLT", "SKAS", 2, "Depart from SKLT and when you are 50nm out of LET, return to land in SKLT."),
    ("SKLT", "SKAS", 2, "Ready for an NDB approach?")
]


def insert_airport_info():
    """Will insert airport information to airport_info table."""
    for item in data:
        db_manager_sqlite.insert_airport_info(
            item[0], item[1], item[2], item[3], item[4],
            item[5], item[6], item[7], item[8], item[9], item[10])

    print("Airport info has been saved!")


def insert_airport_nav_data():
    """Will insert airport information to airport_nav_data table."""

    for item in data:
        db_manager_sqlite.insert_airport_nav_data(
            item[0], item[11], item[12], item[13], item[14],
            item[15], item[16], item[17], item[18], item[19],
            item[20], item[21], item[22])

    print("Airport nav data  has been saved!")


def insert_diff_flight():
    """Will insert flights based on difficulty to the diff_flights table."""
    # diff_flight_data = [
    #     ("SKMZ", "SKAR", 3, "Comentarios Vuelo MZL-AXM")
    # ]

    for data in diff_flight_data:
        db_manager_sqlite.insert_diff_flight(
            data[0], data[1], data[2], data[3])

    print("Diff Flights Info saved!")


# insert_airport_info()
# insert_airport_nav_data()
# insert_diff_flight()
